aliases = [ "es6", "es2015" ]
dependencies = [ "_ESAbstract.CreateMethodProperty", "_ESAbstract.Type" ]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/#sec-isfinite-number"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite"

[browsers]
ie = "*"
firefox = "<16"
chrome = "<19"
safari = "<9"
opera = "<15"

