aliases = [ "es6", "es2015", "modernizr:es6string" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.RequireObjectCoercible",
  "_ESAbstract.ToInteger",
  "_ESAbstract.ToString"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat"
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.repeat"

[browsers]
android = "*"
bb = "*"
chrome = "* - 40"
firefox = "3.6 - 23"
opera = "10 - 18"
safari = "*"
edge = "*"
edge_mob = "*"
ie = "*"
ie_mob = "10 - *"
ios_saf = "*"
firefox_mob = "3.6 - 23"

