aliases = [ ]
dependencies = [
  "Object.defineProperty",
  "Array.prototype.filter",
  "Array.prototype.includes",
  "requestAnimationFrame",
  "performance.now",
  "Event"
]
license = "MIT"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback"

[browsers]
android = "*"
bb = "*"
chrome = "<47"
edge = "*"
edge_mob = "*"
firefox = "<55"
ios_chr = "*"
ios_saf = "*"
ie = "*"
ie_mob = "*"
opera = "<34"
op_mini = "*"
op_mob = "*"
safari = "9 - *"
firefox_mob = "<55"
samsung_mob = "*"

