aliases = [
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "caniuse:requestanimationframe",
  "modernizr:requestanimationframe"
]
dependencies = [ "Date.now" ]
license = "MIT"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame"

[browsers]
android = "*"
bb = "7"
chrome = "1 - 23"
ie = "6 - 9"
ios_saf = "3.2 - 6"
firefox = "3.6 - 22"
opera = "<15"
op_mini = "5 - *"
op_mob = "10 - 12.1"
safari = "3.1 - 6"
firefox_mob = "3.6"

