dependencies = [ "atob", "URL" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob"
license = "MIT"
repo = "https://github.com/eligrey/Blob.js/blob"

[browsers]
chrome = "<20"
edge = "*"
edge_mob = "*"
firefox = "<13"
safari = "<6"
ie = "*"
opera = "<12"

