aliases = [ ]
dependencies = [ "IntersectionObserver", "Object.defineProperty" ]
docs = "https://github.com/w3c/IntersectionObserver/blob/master/explainer.md"
spec = "http://rawgit.com/w3c/IntersectionObserver/master/index.html"
notes = [ ]
repo = "https://github.com/w3c/IntersectionObserver"

[browsers]
edge = "15"
edge_mob = "15"

