aliases = [
    "es2017"
]
dependencies = [
    "Object.getOwnPropertyDescriptor",
    "Object.defineProperty",
    "Reflect.ownKeys",
    "_ESAbstract.ToObject",
    "_ESAbstract.CreateMethodProperty",
    "_ESAbstract.CreateDataProperty",
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors"

[browsers]
ie = "9 - *"
edge = "<15"
chrome = "<54"
firefox = "<50"
safari = "<10"
