dependencies = [ "Array.prototype.forEach" ]
spec = "https://heycam.github.io/webidl/#es-forEach"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach"

[browsers]
edge = "<16"
edge_mob = "<16"
ie = "*"
ie_mob = "*"
chrome = "<51"
firefox = "<50"
opera = "<38"
op_mob = "<38"
safari = "<10"
android = "<51"
firefox_mob = "<50"
ios_saf = "<10"
samsung_mob = "<5"

