dependencies = [ "Array.prototype.reduceRight" ]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.normalize"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"

[install]
module = "unorm"
paths = [ "lib/unorm.js" ]
postinstall = "update.task.js"

