dependencies = [ "Object.defineProperty" ]
notes = [
  "In IE <= 8 window.screen is read-only, so the orientation property is not definable"
]
spec = "http://www.w3.org/TR/screen-orientation/"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation"

[browsers]
edge = "*"
edge_mob = "*"
ie = "9 - *"
ie_mob = "*"
firefox = "*"
chrome = "* - 37"
safari = "*"
ios_saf = "*"
opera = "* - 24"
op_mob = "*"
android = "*"
bb = "*"
firefox_mob = "*"

