aliases = [
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "blissfuljs"
]
dependencies = [ "Element" ]
spec = "http://w3.org/TR/DOM-Level-3-Core/core.html#ID-3A0ED0A4"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode"

[browsers]
ie = "8"
firefox = "<30"

