aliases = [ "es6", "es2015" ]
dependencies = [ "Object.defineProperty" ]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/#sec-number.min_safe_integer"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER"

[browsers]
ie = "*"
ie_mob = "*"
firefox = "<31"
firefox_mob = "<32"
chrome = "<34"
android = "<5"
safari = "<9"
ios_saf = "<9"
opera = "<32"
op_mini = "*"
op_mob = "*"
bb = "*"

