aliases = [
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "es5",
  "modernizr:es5array"
]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToObject",
  "_ESAbstract.ToLength",
  "_ESAbstract.Get",
  "_ESAbstract.IsCallable",
  "_ESAbstract.ToString",
  "_ESAbstract.HasProperty",
  "_ESAbstract.ToBoolean",
  "_ESAbstract.Call"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.every"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every"

[browsers]
ie = "6 - 8"

