aliases = [ ]
dependencies = [ "Element" ]
spec = "https://dom.spec.whatwg.org/#dom-element-toggleattribute"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute"

[browsers]
android = "<69"
bb = "*"
chrome = "<69"
edge = "<18"
edge_mob = "<18"
firefox = "<63"
ios_chr = "<12"
ios_saf = "<12"
ie = "*"
ie_mob = "*"
opera = "<56"
op_mini = "*"
op_mob = "<51"
safari = "<12"
firefox_mob = "<63"
samsung_mob = "*"

