aliases = [ ]
dependencies = [ "XMLHttpRequest" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon"
spec = "https://w3c.github.io/beacon/#sec-sendBeacon-method"
repo = "https://github.com/miguelmota/Navigator.sendBeacon"
license = "MIT"

[browsers]
chrome = "<39"
edge = "*"
edge_mob = "*"
firefox = "<31"
ie = "*"
opera = "<26"
safari = "*"
android = "*"
firefox_mob = "<31"
ie_mob = "*"
op_mob = "*"
ios_saf = "*"

