aliases = [
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "es6",
  "es2015",
  "modernizr:es6string"
]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.RequireObjectCoercible",
  "_ESAbstract.ToString",
  "_ESAbstract.IsRegExp",
  "_ESAbstract.ToInteger"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes"
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.includes"

[browsers]
android = "*"
bb = "*"
chrome = "<=40"
firefox = "<=39"
opera = "10 - 18"
op_mini = "*"
safari = "<9"
edge = "<14"
edge_mob = "<14"
ie = "*"
ie_mob = "10 - *"
ios_saf = "<9"
firefox_mob = "*"

