dependencies = [
  "_ESAbstract.Call",
  "_ESAbstract.GetMethod",
  "_ESAbstract.OrdinaryToPrimitive",
  "_ESAbstract.Type"
]
spec = "https://tc39.github.io/ecma262/#sec-toprimitive"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"

