repo = "https://github.com/JamesMGreene/document.currentScript"
license = "MIT"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript"
spec = "https://html.spec.whatwg.org/multipage/dom.html#dom-document-currentscript"
notes = [
  "This polyfill will not work in IE11 because of a critical design choice made Microsoft (\"Don't Call Me IE!\") [\\[1\\]](https://msdn.microsoft.com/en-us/library/ie/bg182625.aspx)[\\[2\\]](https://msdn.microsoft.com/en-us/library/ie/dn384059.aspx)[\\[3\\]](http://www.nczonline.net/blog/2013/07/02/internet-explorer-11-dont-call-me-ie/)[\\[4\\]](http://blog.getify.com/ie11-please-bring-real-script-preloading-back/) in order to avoid consumers receiving an unnecessarily downgraded experience on websites that were making logic branch and feature decisions based on browser detection rather than feature detection."
]

[browsers]
ie = "8 - 10"

