aliases = [ ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToObject",
  "_ESAbstract.Get",
  "_ESAbstract.ToLength",
  "_ESAbstract.ToString"
]
spec = "https://tc39.github.io/ecma262/#sec-string.raw"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw"

[browsers]
android = "*"
bb = "*"
chrome = "<41"
edge = "<13"
edge_mob = "<13"
firefox = "<34"
firefox_mob = "<34"
ie = "*"
ie_mob = "*"
opera = "<33"
op_mob = "*"
op_mini = "*"
safari = "<10"
ios_chr = "<10"
ios_saf = "<10"
samsung_mob = "<4"

