aliases = [ "es6", "es2015", "modernizr:es6array" ]
dependencies = [
  "_ArrayIterator",
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToObject"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.entries"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/entries"

[browsers]
edge = "<13"
edge_mob = "<13"
ie = "*"
ie_mob = "*"
firefox = "<38"
chrome = "<38"
safari = "<7.1"
android = "<5.1"
ios_saf = "<8"
opera = "<25"
samsung_mob = "<5"

