dependencies = [
  "_Iterator",
  "Object.create",
  "Object.defineProperty",
  "Object.setPrototypeOf",
  "String.prototype.includes"
]
license = "MIT"
repo = "https://github.com/medikoo/es6-iterator"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
ios_chr = "*"
ios_saf = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mini = "*"
op_mob = "*"
safari = "*"
firefox_mob = "*"
samsung_mob = "*"

