aliases = [
  "es6",
  "es2015",
  "modernizr:es6array",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default"
]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToObject",
  "_ESAbstract.ToLength",
  "_ESAbstract.Get",
  "_ESAbstract.ToInteger",
  "_ESAbstract.ToString"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.fill"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill"

[browsers]
ie = "*"
safari = "<= 7"
firefox = "< 31"
chrome = "< 45"
android = "*"
ios_saf = "<= 7"
samsung_mob = "<5"

