aliases = [ ]
dependencies = [ "Symbol", "Object.defineProperty" ]
license = "MIT"
spec = "https://tc39.github.io/proposal-Symbol-description/"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/description"

[browsers]
edge = "*"
edge_mob = "*"
ie = "*"
ie_mob = "*"
safari = "*"
chrome = "< 70"
firefox = "< 63"
firefox_mob = "< 63"
ios_saf = "*"
opera = "< 57"
op_mini = "*"
samsung_mob = "*"
android = "*"
bb = "*"

