dependencies = [ "document.querySelector" ]
spec = "https://dom.spec.whatwg.org/#dom-document-getelementsbyclassname"
docs = "https://developer.mozilla.org/en/docs/Web/API/Document/getElementsByClassName"

[browsers]
ie = "<9"

