aliases = [ "es6", "es2015" ]
dependencies = [ "_ESAbstract.CreateMethodProperty", "_ESAbstract.ToUint32" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul"
spec = "https://tc39.github.io/ecma262/#sec-math.imul"

[browsers]
android = "*"
bb = "*"
chrome = "1 - 27"
edge = "*"
edge_mob = "*"
firefox = "1 - 19"
ie = "*"
ie_mob = "10 - *"
ios_chr = "*"
ios_saf = "4 - 6.1"
opera = "10 - 15"
op_mob = "*"
op_mini = "*"
safari = "4 - 6.1"
firefox_mob = "1 - 19"

