aliases = [ "es6", "es2015" ]
dependencies = [ "Object.defineProperty", "Symbol" ]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/index.html#sec-symbol.match"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol"

[browsers]
edge = "<14"
edge_mob = "<14"
ie = "*"
ie_mob = "*"
safari = "<9"
chrome = "< 50"
firefox = "< 40"
firefox_mob = "< 40"
ios_saf = "< 10"
opera = "< 37"
samsung_mob = "<5"
android = "<50"
bb = "10 - *"

