aliases = [ "es7", "es2016", "modernizr:es7array" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToObject",
  "_ESAbstract.ToLength",
  "_ESAbstract.Get",
  "_ESAbstract.ToInteger",
  "_ESAbstract.SameValueZero",
  "_ESAbstract.ToString"
]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.includes"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes"

[browsers]
chrome = "<47"
edge = "*"
edge_mob = "*"
firefox = "<=42"
ie = "*"
opera = "*"
safari = "<9"
ios_saf = "<9"
ios_chr = "*"
android = "*"
op_mob = "*"
op_mini = "*"
ie_mob = "*"
firefox_mob = "*"
samsung_mob = "<5"
bb = "10 - *"

