aliases = [ "caniuse:namevalue-storage", "modernizr:localstorage" ]
dependencies = [ "Array.prototype.forEach", "Window" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage"
spec = "http://dev.w3.org/html5/webstorage/#dom-localstorage"

[browsers]
ie = "6 - 7"
op_mini = "*"

