aliases = [
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "es5",
  "modernizr:es5array"
]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToObject",
  "_ESAbstract.ToLength",
  "_ESAbstract.Get",
  "_ESAbstract.ToInteger",
  "_ESAbstract.HasProperty",
  "_ESAbstract.ToString"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.lastindexof"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf"

[browsers]
ie = "6 - 8"

