aliases = [ ]
dependencies = [
  "getComputedStyle",
  "Array.isArray",
  "Array.prototype.filter",
  "Array.prototype.forEach",
  "Array.prototype.indexOf",
  "Array.prototype.map",
  "Array.prototype.some",
  "Event",
  "Function.prototype.bind",
  "performance.now"
]
docs = "https://github.com/w3c/IntersectionObserver/blob/master/explainer.md"
spec = "http://rawgit.com/w3c/IntersectionObserver/master/index.html"
notes = [ ]
repo = "https://github.com/w3c/IntersectionObserver"

[browsers]
android = "*"
bb = "*"
chrome = "< 51"
edge = "< 16"
edge_mob = "< 16"
firefox = "< 55"
firefox_mob = "< 55"
ie = "*"
ie_mob = "*"
ios_saf = "< 12.2"
op_mini = "*"
opera = "< 45"
safari = "< 12.2"
samsung_mob = "< 7"

