dependencies = [
  "_ESAbstract.RequireObjectCoercible",
  "_ESAbstract.ToString",
]
spec = "https://tc39.es/ecma262/#sec-createhtml"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
ios_chr = "*"
ios_saf = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mini = "*"
op_mob = "*"
safari = "*"
firefox_mob = "*"
samsung_mob = "*"

