aliases = [ "es2017" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToObject",
  "Array.prototype.map",
  "Object.defineProperty",
  "Object.keys"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values"

[browsers]
edge = "< 14"
edge_mob = "< 14"
ie = "*"
ie_mob = "*"
chrome = "< 54"
ios_chr = "< 54"
safari = "< 10.1"
ios_saf = "< 10.3"
firefox = "< 47"
firefox_mob = "< 47"
android = "< 54"
opera = "< 41"
op_mob = "< 41"
op_mini = "*"
samsung_mob = "< 6"
bb = "*"

