aliases = [ "es6", "es2015" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToInteger",
  "_ESAbstract.Type"
]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/#sec-number.isinteger"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger"

[browsers]
edge = "<13"
edge_mob = "<13"
ie = "*"
ie_mob = "*"
chrome = "<34"
ios_chr = "*"
safari = "<9"
ios_saf = "<9"
firefox = "<16"
firefox_mob = "*"
android = "<5"
opera = "<22"
op_mob = "*"
op_mini = "*"
samsung_mob = "<5"
bb = "*"

