dependencies = [
  "_ESAbstract.Type",
  "_ESAbstract.ToLength",
  "_ESAbstract.Get",
  "_ESAbstract.ToString",
  "Array.prototype.includes"
]
spec = "https://tc39.github.io/ecma262/#sec-createlistfromarraylike"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
ios_chr = "*"
ios_saf = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mini = "*"
op_mob = "*"
safari = "*"
firefox_mob = "*"
samsung_mob = "*"

