aliases = [ "caniuse:matchmedia", "modernizr:matchmedia" ]
dependencies = [ "Event" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia"
spec = "http://dev.w3.org/csswg/cssom-view/#the-mediaquerylist-interface"

[browsers]
android = "2.1 - 2.3"
blackberry = "7"
ie = "<9"
opera = "11.5 - 12.1"
op_mini = "*"
op_mob = "10 - 12"
safari = "4 - 5"

