aliases = []
dependencies = [
  "Object.defineProperties"
]
spec = "https://www.w3.org/TR/geometry-1/#DOMRect"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/DOMRect"

[browsers]
ie = "9 - *"
ie_mob = "9 - *"
chrome = "<60"
ios_chr = "<10.1"
safari = "<10.1"
ios_saf = "<10.1"
firefox = "<=30"
android = "<6"
