dependencies = [
  "_ESAbstract.Get",
  "_ESAbstract.Type",
  "Object.getOwnPropertyDescriptor",
  "Object.keys"
]
spec = "https://tc39.github.io/ecma262/#sec-enumerableownproperties"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"

