dependencies = [
  "_ESAbstract.IsArray",
  "_ESAbstract.ArrayCreate",
  "_ESAbstract.Get",
  "_ESAbstract.Type",
  "_ESAbstract.IsConstructor",
  "_ESAbstract.Construct"
]
spec = "https://tc39.github.io/ecma262/#sec-arrayspeciescreate"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"

