dependencies = [
  "Array.prototype.forEach",
  "Object.getOwnPropertyNames",
  "Promise",
  "XMLHttpRequest",
  "Symbol.iterator"
]
license = "MIT"
spec = "https://fetch.spec.whatwg.org/"
repo = "https://github.com/github/fetch"
notes = [
  "Makes use of FormData, FileReader and Blob if they exist. Readable streams not supported. CORS (Cross Origin Resource Sharing) requests do not work in IE 9 or lower."
]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch"

[browsers]
android = "<67"
bb = "10 - *"
edge = "<16"
edge_mob = "<16"
ie = "*"
ie_mob = "*"
firefox = "<57"
opera = "<53"
safari = "<12"
chrome = "<66"
ios_saf = "<12"
firefox_mob = "<64"

[install]
module = "whatwg-fetch"
postinstall = "update.task.js"
