aliases = [ ]
dependencies = [ ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment"
spec = "https://dom.spec.whatwg.org/#interface-documentfragment"
notes = [ ]

[browsers]
android = "<3"
firefox = "<4"
ios_chr = "<4"
ios_saf = "<4"
ie = "8 - 9"
ie_mob = "<9"
opera = "<11"
op_mini = "<11"
safari = "<4"
firefox_mob = "<4"
samsung_mob = "<3"

