aliases = [ "es6", "es2015", "modernizr:es6array" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "Array.prototype.values",
  "Symbol.iterator"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype-@@iterator"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator"

[browsers]
edge = "<13"
edge_mob = "<13"
ie = "*"
ie_mob = "*"
firefox = "<38"
chrome = "<49"
safari = "<9"
android = "<5.1"
ios_saf = "<9"
opera = "<25"
samsung_mob = "<5"

