aliases = [
  "es5",
  "modernizr:es5object",
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "blissfuljs"
]
dependencies = [ ]
notes = [
  "In browsers that have no hooks to define getter functions (notably IE <= 8), attempting to defineProperty with a getter or setter function will fail.  Since failing silently would likely break your application, we throw an exception.  In IE8, this can be hard to diagnose because the console will just say 'Exception thrown and not caught'"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty"

[browsers]
firefox = "3.6"
safari = "4 - 4.1"
ios_saf = "4.3"
firefox_mob = "3.6"
ie = "6 - 8"

