aliases = [ "es6", "es2015" ]
dependencies = [
  "_ESAbstract.Get",
  "_ESAbstract.ToBoolean",
  "_ESAbstract.Type",
  "Object.defineProperty"
]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-get-regexp.prototype.flags"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags"

[browsers]
edge = "<13"
edge_mob = "<13"
firefox = "<37"
ie = "9 - 12"

