aliases = [
  "Int8Array",
  "Uint8Array",
  "Uint8ClampedArray",
  "Int16Array",
  "Uint16Array",
  "Int32Array",
  "Uint32Array",
  "Float32Array",
  "Float64Array",
  "DataView",
  "ArrayBuffer"
]
license = "MIT"
repo = "https://github.com/inexorabletash/polyfill"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"

[install]
module = "js-polyfills"
paths = [ "typedarray.js" ]

