aliases = [ "es7", "es2016", "es2017" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.RequireObjectCoercible",
  "_ESAbstract.ToString",
  "_ESAbstract.ToLength"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart"

[browsers]
android = "*"
bb = "*"
chrome = "<57"
firefox = "<48"
opera = "<44"
safari = "<10"
edge = "<15"
edge_mob = "<15"
ie = "*"
ie_mob = "*"
ios_saf = "<10"
firefox_mob = "<48"
samsung_mob = "*"

