aliases = [ "default-3.4", "default-3.5", "default-3.6", "default" ]
dependencies = [ "Object.defineProperties" ]

[browsers]
ie = "6 - 10"
ie_mob = "10"
firefox = "<=20"
safari = "<=6"
ios_saf = "<=6"
chrome = "<=29"
firefox_mob = "<=20"

