aliases = [ "es6", "es2015" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.RequireObjectCoercible",
  "_ESAbstract.ToString",
  "_ESAbstract.ToInteger",
  "_ESAbstract.UTF16Decode"
]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.codepointat"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt"

[browsers]
chrome = "<41"
firefox = "<29"
ie = "*"
opera = "<28"
safari = "<10"

