aliases = [ "default-3.4", "default-3.5", "default-3.6", "default" ]
dependencies = [
  "document",
  "Element",
  "Array.prototype.indexOf",
  "_mutation"
]
spec = "http://dom.spec.whatwg.org/#dom-childnode-after"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/after"

[browsers]
android = "*"
bb = "*"
chrome = "<54"
edge = "*"
edge_mob = "*"
firefox = "<49"
ios_chr = "*"
ios_saf = "<10"
ie = "6 - *"
ie_mob = "10 - *"
opera = "*"
op_mini = "*"
safari = "<10"
firefox_mob = "<49"
samsung_mob = "<6"

