aliases = [
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "blissfuljs"
]
dependencies = [ "Event" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest"

[browsers]
ie = "6 - 8"

