alias = [ "HTMLCanvasElement.protoype.toBlob" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_TypedArray",
  "atob",
  "Blob"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob"
license = "MIT"

[browsers]
chrome = "<50"
edge = "*"
edge_mob = "*"
firefox = "<19"
safari = "<11"
ie = ">=10"
opera = "*"
ios_saf = "<11"

