aliases = [ "es6", "es2015" ]
dependencies = [ "_ESAbstract.CreateMethodProperty", "_TypedArray" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/fround"
spec = "https://tc39.github.io/ecma262/#sec-math.fround"

[browsers]
android = "*"
bb = "*"
chrome = "<37"
firefox = "<26"
ie = "9 - 11"
ie_mob = "*"
ios_chr = "*"
ios_saf = "<8"
opera = "<25"
op_mob = "*"
op_mini = "*"
safari = "<8"
firefox_mob = "<26"

