aliases = [
  "caniuse:geolocation",
  "modernizr:geolocation",
  "Navigator.prototype.geolocation"
]
dependencies = [ "document.head" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation"
spec = "http://www.w3.org/TR/geolocation-API/#navi-geo"

[browsers]
ie = "<9"
opera = "15"
safari = "4"

