dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.ToObject",
  "_ESAbstract.ToLength",
  "_ESAbstract.Get",
  "_ESAbstract.ToInteger",
  "_ESAbstract.ArraySpeciesCreate",
  "_ESAbstract.FlattenIntoArray"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.flat"

[browsers]
android = "*"
bb = "*"
chrome = "< 69"
edge = "*"
edge_mob = "*"
firefox = "< 62"
firefox_mob = "< 62"
ie = "*"
ie_mob = "*"
ios_chr = "< 12"
ios_saf = "< 12"
op_mini = "*"
op_mob = "*"
opera = "< 56"
safari = "< 12"
samsung_mob = "*"

