aliases = [
  "es5",
  "modernizr:es5object",
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "blissfuljs"
]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.Type",
  "Object.defineProperties"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create"

[browsers]
ie = "6 - 8"
safari = "4"
firefox = "<4"
firefox_mob = "<4"

