dependencies = [
  "_ESAbstract.Call",
  "_ESAbstract.GetMethod",
  "_ESAbstract.GetV",
  "_ESAbstract.Type",
  "Object.create",
  "Symbol.iterator"
]
spec = "https://tc39.github.io/ecma262/#sec-getiterator"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"

