aliases = [ ]
dependencies = [ ]
spec = "https://html.spec.whatwg.org/multipage/comms.html#the-eventsource-interface"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/EventSource"
license = "MIT"
repo = "https://github.com/Yaffle/EventSource"

[browsers]
firefox = "<36"
chrome = "<26"
edge = "*"
edge_mob = "*"
safari = "<7"
opera = "<12"
ie = "*"
ie_mob = "*"
android = "<4.4"

[install]
module = "event-source-polyfill"
paths = [ "./src/eventsource.js" ]

