aliases = [
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "caniuse:datauri"
]
license = "MIT"
repo = "http://www.webtoolkit.info/javascript-base64.html"
spec = "https://html.spec.whatwg.org/multipage/webappapis.html#dom-windowbase64-atob"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/atob"

[browsers]
ie = "<10"

[install]
module = "Base64"
paths = [ "base64.js" ]

