dependencies = [ "Date.now" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Performance/now"

[browsers]
android = "<=4.3"
bb = "<10"
chrome = "<24"
ie = "<10"
ios_saf = "<9"
firefox = "<15"
opera = "<15"
op_mini = "*"
op_mob = "<24"
safari = "<8"
firefox_mob = "<15"

