aliases = [ "es6", "es2015" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "Array.prototype.forEach",
  "Object.create",
  "Object.defineProperty",
  "Object.getPrototypeOf",
  "Object.getOwnPropertyNames",
  "Object.getOwnPropertyDescriptor"
]
license = "MIT"
docs = "https://tc39.github.io/ecma262/#sec-object.setprototypeof"
repo = "https://github.com/paulmillr/es6-shim/"

[browsers]
android = "*"
bb = "*"
chrome = "< 34"
firefox = "< 31"
ios_chr = "*"
ios_saf = "< 9"
ie = "9 - 11"
ie_mob = "*"
opera = "< 34"
op_mini = "*"
safari = "< 9"
firefox_mob = "< 31"

