repo = "https://github.com/megawac/MutationObserver.js"
docs = "https://developer.mozilla.org/en/docs/Web/API/MutationObserver"
spec = "https://dom.spec.whatwg.org/#mutationobserver"
license = "WTFPL"

[browsers]
chrome = "<26"
edge = "*"
edge_mob = "*"
firefox = "<14"
ie = "*"
opera = "<15"
safari = "<6"
android = "<4.4"
firefox_mob = "<14"
ie_mob = "<11"
op_mob = "<15"
ios_saf = "<7"

[install]
module = "mutationobserver-shim"
paths = [ "MutationObserver.js" ]

