aliases = [
  "modernizr:urlparser",
  "blissfuljs",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "URLSearchParams"
]
dependencies = [
  "Object.defineProperties",
  "Array.prototype.forEach",
  "Array.isArray"
]
notes = [ "Polyfill requires Object getters so fails in IE < 8" ]
license = "CC0-1.0"
repo = "https://github.com/inexorabletash/polyfill"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/URL"

[browsers]
chrome = "<51"
firefox = "<44"
edge = "*"
edge_mob = "*"
ie = "9 - *"
ie_mob = "*"
safari = "<12"
firefox_mob = "<44"
opera = "<36"
op_mini = "*"
android = "*"
samsung_mob = "<5"
bb = "*"
ios_saf = "<12"

