dependencies = [
  "_ESAbstract.GetPrototypeFromConstructor",
  "Object.create",
  "Object.defineProperty",
  "Object.getPrototypeOf"
]
spec = "https://tc39.github.io/ecma262/#sec-ordinarycreatefromconstructor"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"

