dependencies = [ "_ArrayIterator", "Symbol.iterator", "DOMTokenList" ]
license = "MIT"
spec = "https://dom.spec.whatwg.org/#domtokenlist"

[browsers]
edge = "<13"
edge_mob = "<13"
ie = "9-12"
ie_mob = "9 - 12"
safari = "<9"
chrome = "<50"
firefox = "<40"
ios_saf = "*"
opera = "<50"
samsung_mob = "<5"
bb = "10 - *"

