aliases = [ "es6", "es2015" ]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.HasProperty",
  "_ESAbstract.ToInteger"
]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.copywithin"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin"

[browsers]
edge = "*"
edge_mob = "*"
chrome = "<45"
firefox = "<32"
ie = "*"
safari = "<9"
opera = "<32"

