aliases = [
  "es5",
  "modernizr:es5object",
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default"
]
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.Get",
  "_ESAbstract.ToObject",
  "_ESAbstract.Type",
  "Object.keys",
  "Object.getOwnPropertyDescriptor",
  "Object.defineProperty"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties"

[browsers]
ie = "6 - 8"
safari = "4 - 4.1"
firefox = "<4"
firefox_mob = "<4"

