aliases = [ "es2018" ]
dependencies = [ "Object.defineProperty", "Symbol" ]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/index.html#sec-symbol.asyncIterator"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator"

[browsers]
edge = "*"
edge_mob = "*"
ie = "*"
ie_mob = "*"
safari = "< 11.1"
chrome = "< 63"
firefox = "< 55"
ios_saf = "< 11.1"
opera = "< 50"
samsung_mob = "*"
android = "< 63"
bb = "*"

