aliases = [
  "default-3.3",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default"
]
dependencies = [ "Window", "document", "Element", "Object.defineProperty" ]
docs = "https://developer.mozilla.org/en/docs/Web/API/Event"
notes = [
  "Where necessary, also adds the [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) methods `addEventListener`, `removeEventListener` and `dispatchEvent`."
]

[browsers]
firefox = "6 - 10"
ie = "6 - 11"
ie_mob = "10"
opera = "10 - 11.5"
safari = "4 - 7"
firefox_mob = "6 - 10"

