aliases = [ "default-3.4", "default-3.5", "default-3.6", "default" ]
dependencies = [ "document", "Element", "_mutation" ]
spec = "http://dom.spec.whatwg.org/#dom-childnode-remove"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove"

[browsers]
android = "*"
bb = "*"
chrome = "* - 28"
edge = "<14"
edge_mob = "<14"
firefox = "<45"
ios_chr = "*"
ios_saf = "<9"
ie = "*"
ie_mob = "10 - *"
opera = "* - 15"
op_mini = "*"
safari = "<9.1"
firefox_mob = "3.6 - *"

